### ISSUE TITLE
Multiple builds on a PR fails to update final status

### ISSUE THREAD

**Issue by mschroering** [jenkinsci/github-checks-plugin#50] opened 2020-09-10 15:08 UTC
I have noticed that when multiple commits are made to a PR and then multiple builds in Jenkins are then ran for those commits, that the final Jenkins check status does not get updated and stays stuck in the "Queued" state.  In this case, each build is failing due to a legitimate lint failure.  Looking at the build logs, I can see that it appears to be publishing the updates, but looking at the PR in github, the check status never gets updated. 

```
11:01:09  [GitHub Checks] GitHub check (name: Jenkins, status: IN_PROGRESS) has been published.
...
11:01:43  [GitHub Checks] GitHub check (name: Jenkins, status: IN_PROGRESS) has been published.
...
11:02:01  [GitHub Checks] GitHub check (name: Jenkins, status: IN_PROGRESS) has been published.
...
11:02:43  [GitHub Checks] GitHub check (name: Jenkins, status: COMPLETED) has been published.
```

![Screenshot-20200910110822-699x218](https://user-images.githubusercontent.com/1280524/92751444-f7992500-f355-11ea-98d2-04a1ded007cf.png)

![Screenshot-20200910110805-587x241](https://user-images.githubusercontent.com/1280524/92751452-f962e880-f355-11ea-9b8b-4d57dc4e6e0d.png)

This is testing on an internal repo, so I cannot share links to it directly.

**Comment by XiongKezhi** [comment] 2020-09-10 15:44
Thanks for your report!

Usually, the log will be updated only after receiving a success response from GitHub after creating checks. In which kind of project are you publishing these checks, multi-branch, or GitHub org repository? Did you meet many times like this when you are using the plugins? I'll try to reproduce that.

**Comment by mschroering** [comment] 2020-09-10 16:00
This is in a Github org repository.  I've been able to reproduce in a couple of repos now.  The first commit/build seems to update fine as you can see in the screenshot above with the build failure.  Subsequent builds though seem to not get updated.

**Comment by petersendidit** [comment] 2020-09-11 15:28
We are seeing the exact same issue with a multibranch pipeline. The Jenkins log shows `[GitHub Checks] GitHub check (name: Jenkins, status: COMPLETED) has been published.` but the PR in GitHub stays as `Jenkins Queued — Waiting to run this check...`

**Comment by tim-dawson-nv** [comment] 2020-09-22 05:29
I am seeing something similar, with github branch source plugin. where a PRs are merged before execing the pipeline.

`[GitHub Checks] Failed Publishing GitHub checks: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/xxxxxxx/xxxxx/check-runs {"message":"No commit found for SHA: zzzzzzzzzzzzzzzzzzzzzzzzzzzzz","documentation_url":"https://docs.github.com/rest/reference/checks#create-a-check-run"}`

Looks like the first job start gets logged but after the merged branch is checked out no other checks are published.

**Comment by XiongKezhi** [comment] 2020-10-06 08:52
sorry, I find it difficult to reproduce this issue, I tried a couple of times: https://github.com/XiongKezhi/codingstyle/pull/1, there are some "in progress" checks, but they are merged from other branches before their corresponding builds' finishing, not a simple commit; and the final checks are always working.

can you show me some steps on how you reproduced them?

**Comment by mschroering** [comment] 2020-10-06 10:32
We were seeing it when this happened:

1. Open PR
2. First Jenkins build  completes and the Check status is set to completed
3. Push a new commit to the branch to trigger another Jenkins build
4. New Jenkins build starts, the Check status changes to "Queued"
5. Jenkins build completes

Expected results:
The Check status gets updated to in progress and then completed when the Jenkins build completes

Actual results:
The Check status stays stuck in the "Queued" state.

**Comment by XiongKezhi** [comment] 2020-10-07 08:45
Is the PR created from the origin repo or forked repo?

Can I get your Jenkinsfile? You can remove the sensitive configs.

**Comment by ryanmoon** [comment] 2020-10-15 19:25
Seeing the same issue.

Origin repo.

Sanitized Jenkinsfile here: https://gist.github.com/ryanmoon/d2fb892338f34f10b3aaad12be82759a

Seeing on this on version 1.0.0 and the latest.

**Comment by timja** [comment] 2020-10-23 20:25
Found how to reproduce, add a global pipeline library, should be easy to fix hopefully

**Closed** 2020-10-24 03:30 UTC
Labels: bug, more information needed
